### ISSUE TITLE
questions about firebird versions (2.5 / 3.0) and strings charset encoding 

### ISSUE THREAD

**Issue by solyarisoftware** [hgourvest/node-firebird#221]
Hello
this is not a issue, but just small info requests, I'm newbie to Firebird and this project. BTW, Thanks for all!

1. "Pure JavaScript and Asynchronous Firebird client for Node.js"
"Pure Javascript" does it means that the TCP client-server protocol is written in JS. So you didn't use the C++ client library, right?  
"Asynchronous" does it means that you just followed the nodejs callback behavior, right? 

2. Is this library suitable for both 2.5 and 3.0 firebird database versions?
I Just tested a firebird 3.0 db remote connection an it works fine. I need to change/configure somthing to connect to a old (2.5) DB?

3. When I do a query like:

```
//
// SQL> CREATE TABLE PEOPLE (ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(25));
// SQL> INSERT INTO PEOPLE VALUES (1, 'Angelo');
// SQL> INSERT INTO PEOPLE VALUES (3, 'Giorgio');
// SQL> INSERT INTO PEOPLE VALUES (2, 'Danilo');
//
 
db.query('SELECT * FROM PEOPLE', function(err, result) {
      console.log(result)
      // ...
}
```

VARCHAR columns are returned as Buffers:

```
[
  { ID: 1, NAME: <Buffer 41 6e 67 65 6c 6f> },
  { ID: 3, NAME: <Buffer 47 69 6f 72 67 69 6f> },
  { ID: 2, NAME: <Buffer 44 61 6e 69 6c 6f> }
]
```
So I need to convert Buffers to Strings expicitely:

```
db.query('SELECT * FROM PEOPLE', function(err, result) {
      result.forEach( row => console.log( row.ID, row.NAME.toString() ) )
      //...
}
```

```
1 Angelo
3 Giorgio
2 Danilo
```

Just for curiosity, why VARCHARS are returned as Buffers data type and not as Strings?

Thanks again
giorgio

**Comment by pomgui** [comment]
Hi, I'm not a collaborator of this project, but I'm using it actively, so let me try to answer your questions:

1. Yes
2. Yes. I've only had problems when I connected to 3.0 because I haven't properly read the [Firebird 3.0 Support](https://github.com/hgourvest/node-firebird#firebird-30-support) section in the readme file. So, it was really my fault.
3. That happens because the PEOPLE.NAME field is defined with character set OCTECTS instead of UTF8. You can resolve it either: 
   a. Altering the field:
    ```sql
    ALTER TABLE PEOPLE ALTER NAME TYPE VARCHAR(25) CHARACTER SET UTF8;
    ```
    b. Even better, changing the database default character set before the table creation, so the PEOPLE and any new table would use utf8 by default:
    ```sql
    ALTER DATABASE SET DEFAULT CHARACTER SET UTF8;
    ```

**Comment by solyarisoftware** [comment]
Thanks @pomgui , great answer!


Answer 3 has made the issue clear!

In my example i didn't set che char set:

```
SQL> show database;
Database: /var/lib/firebird/3.0/data/test.fdb
        Owner: SYSDBA
PAGE_SIZE 8192
Number of DB pages allocated = 196
Number of DB pages used = 184
Number of DB pages free = 12
Sweep interval = 20000
Forced Writes are ON
Transaction - oldest = 31
Transaction - oldest active = 32
Transaction - oldest snapshot = 32
Transaction - Next = 36
ODS = 12.0
Database not encrypted
Default Character set: NONE

```

But  isn't all this in conflict with statement here:
https://github.com/hgourvest/node-firebird#charset-for-database-connection-is-always-utf-8  ?

I mean: if I want to manage VARCHAR as String in nodejs, 
- I need to have the table or the database set with UTF8 encoding, 
- Or I manage id dynamically converting each Buffer field to String, e.g. 

`result.forEach( row => console.log( row.ID, row.NAME.toString() ) )

That's correct?
Thanks again

`

**Comment by pomgui** [comment]
Hi @solyarisoftware, 

I'm not completely sure about this, so please take it with a little of salt: I think that Firebird server is who takes care of the transliteration from server's character set to client's character set. Node-firebird driver informs to the server that the client speaks only "utf8" (when attach to firebird), so the server returns all the strings with the correct transliteration.

However, the character set NONE can't be transliterated, because there's no information about what's the content of the field (See what is said about it in the page 59 of [this pdf](https://www.firebirdsql.org/file/community/ppts/fbcon11/FbCon2011-Charsets-Heymann.pdf). In other words it's basically like a [VAR]BINARY field), so firebird returns it as binary (Buffer in js).

As an example, let's get the same 4 characters using different character sets in the same query (using node-firebird):

```sql
SELECT 
    cast('Ação' as varchar(10) character set win1252) from_win1252,
    cast('Ação' as varchar(10) character set ISO8859_1) from_8859_1,
    cast('Ação' as varchar(10) character set none) from_none
FROM RDB$DATABASE
```

Resulting the following json:
```javascript
[ { FROM_WIN1252: 'Ação',
    FROM_8859_1: 'Ação',
    FROM_NONE: <Buffer 41 c3 a7 c3 a3 6f> } ]
```
Firebird correctly transliterated from win1252 and iso8859-1, but not from NONE returning 6 bytes that the client needs to interpret by itself (in a binary can be any kind of information, not only strings).

**Comment by solyarisoftware** [comment]
It's time to close the issue. Thanks @pomgui for all info!
