### ISSUE TITLE
Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.

### ISSUE THREAD

**Issue by wadweb** [hgourvest/node-firebird#290]
Hi there,

We get often the error: Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login. What do we do wrong?
See the test below:

Windows 10 / Windows server, Firebird 3:

```
const Firebird = require('node-firebird');
let count = 0

let options = {};
  options.host = 'localhost';
  options.port = 3050;                      
  options.database = 'C:/test/TEST.FDB';
  options.user = 'SYSDBA';
  options.password = 'masterkey';
  options.lowercase_keys = false; // set to true to lowercase keys
  options.role = null;            // default
  options.pageSize = 4096;        // default when creating database  
  options.retryConnectionInterval = 100; // rec

function test() {
  console.log("start test");
  Firebird.attach(options, function (errConnection, db) {
    if (errConnection) {
      console.log(errConnection);
    }
    db.query("select * from MON$ATTACHMENTS", function (err, result) {
      console.log(++count, result.length);
      db.detach(function (err) {
        console.log(err,"detach");
      });
    });
  });
}

const intervalObj = setInterval(() => {
  test();
}, 500); 
```

C:\test-backoffice>node test2
start test
1 3
undefined detach
start test
2 3
undefined detach
start test
3 3
undefined detach
start test
4 3
undefined detach
start test
Error: Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
    at doCallback (C:\test-backoffice\node_modules\node-firebird\lib\index.js:1321:21)
    at C:\test-backoffice\node_modules\node-firebird\lib\index.js:3100:25
    at C:\test-backoffice\node_modules\node-firebird\lib\messages.js:151:25
    at search (C:\test-backoffice\node_modules\node-firebird\lib\messages.js:117:13)
    at C:\test-backoffice\node_modules\node-firebird\lib\messages.js:54:21
    at FSReqCallback.wrapper [as oncomplete] (node:fs:681:5) {
  gdscode: 335544472,
  gdsparams: undefined
}

**Comment by hcrufio88** [comment]
any news about this? is a real problem!

**Comment by Gobbo89** [comment]
According to the [README section about Firebird 3 support](https://github.com/hgourvest/node-firebird#firebird-30-support), the [wire protocol](https://firebirdsql.org/file/documentation/html/en/firebirddocs/wireprotocol/firebird-wire-protocol.html) **is not** supported.

I've been using node-firebird since release 0.9.9 and back then the only way to make it work, was to follow the instructions provided in the README by editing your firebird.conf.
Or, in some cases, to edit your **database.conf**, f.e.:
```
db_alias = /db_path/db_file_name.fdb
{
    AuthServer = Srp, Legacy_Auth
}
```


At some point ([release 1.1.3](https://github.com/hgourvest/node-firebird/releases/tag/v1.1.3)) compatibility with  wire protocol version >= 13 has been added (it goes like wire protocol 11 = Firebird 2.1, 12 = Firebird 2.5, 13 = Firebird 3, ...).

Please note that the readme didn't get updated, and it is still reporting node-firebird as not supporting the wire protocol.

As a consequence, if you are using node-firebird 1.1.3 or higher, your code might work without adding the Legacy_Auth method in your firebird.conf / database.conf. However, you might occasionally run into error engine code 335544472.

You can try to understand why this is happening, and do a PR if you find a fix.
Or, if possible in your scenario, you should follow the instructions provided in the [README](https://github.com/hgourvest/node-firebird#firebird-30-support) and enable the Legacy_Auth method.

**Comment by wadweb** [comment]
@Gobbo89 , Thanks a lot. This fixed my problem and now no connection error  335544472.
