### ISSUE TITLE
Date and time zone

### ISSUE THREAD

**Issue by xdenser** [hgourvest/node-firebird#3]
```
var con =  new fb.Database('127.0.0.1', 3050, cfg.db, cfg.user, cfg.password,function(){
    con.execute("select Date 'today' from rdb$database", function(rs){
         console.log(rs.data.length);
         console.log(rs.data[0][0]);
    });    
});
```

outputs

```
[xdenser@localhost node-firebird]# node date-issue.js
1
Sat, 09 Jun 2012 00:00:00 GMT
```

while

```
[xdenser@localhost node-firebird]# date -u
Fri Jun  8 22:23:17 UTC 2012
```

Same applies to timestamp and time fields.

**Comment by JohannesHoffmann** [comment]
This issue is not working in my case.
**Problem:**
A select with a date field outputs:
```
Date in Firebird: 2018-08-26
Output in node: 2018-08-25T22:00:00.000Z
```

My server has a timezone Berlin with UTC DST offset from +120 minutes.
The output of d.getTimezoneOffset(); says -120.
Changing the plus to minus solved the problem, see:
`d.setMilliseconds((ret - DateOffset) * TimeCoeff - d.getTimezoneOffset() * MsPerMinute)`

This is my first problem encountered with timezones so i have no idea why this is a problem?

**Comment by r03** [comment]
I think that fix should be optional.  It depends on how you save the date in your database. With current timezone or without it (UTC).
